// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_new_cannonball = "CgkI0ovK6bIQEAIQCA"; // <GPGSID>
        public const string achievement_prime_expert = "CgkI0ovK6bIQEAIQBw"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI0ovK6bIQEAIQAQ"; // <GPGSID>
        public const string achievement_prime_novice = "CgkI0ovK6bIQEAIQAg"; // <GPGSID>
        public const string achievement_ultimate_prime_defender = "CgkI0ovK6bIQEAIQCg"; // <GPGSID>
        public const string achievement_prime_intermediate = "CgkI0ovK6bIQEAIQBg"; // <GPGSID>
        public const string achievement_skin_to_win = "CgkI0ovK6bIQEAIQCQ"; // <GPGSID>
        public const string achievement_beginner_candy_crusher = "CgkI0ovK6bIQEAIQAA"; // <GPGSID>

}

